name: TEST - GET Voting minutes workflow

on:
 workflow_dispatch:
    inputs:
      username:
        description: "GitHub username or org name"
        required: true
        type: string
      branch:
        description: "Branch to test from"
        required: false
        default: "main"
        type: string

jobs:
  test-run:
    uses: ./.github/workflows/liquor-license-applicant-pipeline.yml
    with:
      target-repository: "${{ github.repository_owner }}/boston-liquor-license-tracker"
      target-ref: ${{ github.ref_name }}